### ISSUE TITLE
Error: reporter "wdio-html-format-reporter" is not installed. Error: Error: Cannot find module 'pngjs'

### ISSUE THREAD

**Issue by karl0ss** [aruiz-caritsqa/wdio-html-format-reporter#10]
Have added the module as a devDep

`    "wdio-html-format-reporter": "^0.2.9",`

And have yarn installed, I can see wdio-html-format-reporter in my node_modules

I have added the format to my config 

`  reporters: ['spec', 'allure', 'html-format'],
  reporterOptions: {
    allure: {
      outputDir: './tests/reports/allure'
    },
    htmlFormat: {
      outputDir: './tests/reports/html'
    }
  },`

But when I execute my tests I am getting 

```
yarn run wdio tests/helpers/configs/wdio.CHROMEHEADLESS.conf.js

yarn run v1.9.4
$ /Users/a8907941/Documents/BJSS/Luxon/node_modules/.bin/wdio tests/helpers/configs/wdio.CHROMEHEADLESS.conf.js
/Users/a8907941/Documents/BJSS/Luxon/node_modules/webdriverio/build/lib/launcher.js:163
                        throw _iteratorError;
                        ^

Error: reporter "wdio-html-format-reporter" is not installed. Error: Error: Cannot find module 'pngjs'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/a8907941/Documents/BJSS/Luxon/node_modules/wdio-html-format-reporter/lib/reporter.js:10:13)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Launcher.initReporters (/Users/a8907941/Documents/BJSS/Luxon/node_modules/webdriverio/build/lib/launcher.js:140:35)
    at new Launcher (/Users/a8907941/Documents/BJSS/Luxon/node_modules/webdriverio/build/lib/launcher.js:73:31)
    at launch (/Users/a8907941/Documents/BJSS/Luxon/node_modules/webdriverio/build/lib/cli.js:452:24)
    at Object.<anonymous> (/Users/a8907941/Documents/BJSS/Luxon/node_modules/webdriverio/build/lib/cli.js:485:5)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
error Command failed with exit code 1.
```

Any ideas?

Thanks

**Comment by karl0ss** [comment]
I was able to fix this by added pngjs as a devdependancy in my project...
